### ISSUE TITLE
Documentation / Workflow - Override Work Item Template

### ISSUE THREAD

**Issue by davidkassa** [jelledruyts/TfsTeamProjectManager#23]
Hi, I'm trying to understand how I can use this tool to override completely the work item configurations. I'm upgrading from TFS 2010 and we've never used the work items so I'd like to just change them all to 'Agile' and start over. Is the some combination of the compare and transform tabs that I should be looking at?

**Comment by jelledruyts** [comment]
If you've never used work items then you could just get the work item types from the process template you want to use and upload them to your project (and delete the ones you don't want). Alternatively (because there's more to a process template than just the work items, e.g. process config etc), I usually recommend simply creating a new team project with the desired process and moving the source code over (e.g. by branching into the new project so you retain full history).
